### ISSUE TITLE
404: ZF 2.3 View Helpers page missing

### ISSUE THREAD

**Issue by Martin-P** [zendframework/zf-web#148]
The page about view helpers is missing in the ZF 2.3 manual.

Affected page: http://framework.zend.com/manual/2.3/en/modules/zend.view.view-event.html
Clicking [View Helpers »](http://framework.zend.com/manual/2.3/en/modules/zend.view.helpers.html) results in a 404 page.

**Comment by weierophinney** [comment]
Typically, this is either (a) a caching issue, or (b) pages missing from the latest build of the manual. Both are rather tricky to reproduce and catch even with automation. :-/
