### ISSUE TITLE
404 on advanced ACL

### ISSUE THREAD

**Issue by countless-integers** [zendframework/zf-web#152]
http://framework.zend.com/manual/2.3/en/modules/zend.permissions.acl.advanced.html generated from nav on http://framework.zend.com/manual/2.3/en/modules/zend.permissions.acl.refining.html

**Comment by weierophinney** [comment]
Try going to http://framework.zend.com/manual/current/en/modules/zend.permissions.acl.advanced.html

I think the `2.3` link is a cache hit -- it should be redirected normally.
