### ISSUE TITLE
Prefix the Discus widget on manual pages with a notice about StackOverflow / IRC / Bug Tracker

### ISSUE THREAD

**Issue by adamlundrigan** [zendframework/zf-web#172]
Split from https://github.com/zendframework/zf2-documentation/issues/1287

> A comment as bug report is always a bad idea. Maybe we can add a note to the comment section.

**Comment by adamlundrigan** [comment]
Looks like it would go above this line: https://github.com/zendframework/zf-web/blob/e2541b04eabd23da876b6f42eabc54a1ce888e93/module/Manual/view/manual/page-controller/manual.phtml#L49

**Comment by froschdesign** [comment]
Maybe:

> If you think you have found a bug on this page, please use our bugtracker (link).

or

> No support will be given in the comments / discussion, please use our bugtracker (link).

(The link is a direct link to the bugtracker of the current component.)
