### ISSUE TITLE
incorrect components tag links

### ISSUE THREAD

**Issue by svycka** [zendframework/zf-web#176]
example:
https://github.com/zendframework/zend-eventmanager/releases/tag/3.0.1 
should be
https://github.com/zendframework/zend-eventmanager/releases/tag/release-3.0.1

**Comment by froschdesign** [comment]
Sorry for the very late response but this an old and outdated repository. (will be archived)
Fixed with https://github.com/zendframework/zf3-web/pull/111

Thanks for reporting! 👍
