### ISSUE TITLE
Remove Pyrus from installation methods

### ISSUE THREAD

**Issue by Ocramius** [zendframework/zf-web#181]

**Comment by ezimuel** [comment]
@Ocramius for the new web site, I'm working on this repo https://github.com/ezimuel/zf3-web

**Comment by froschdesign** [comment]
@weierophinney 
Must be changed in the (old) manual files on the server and in all related blog posts. Or ignore it – the decision is up to you as a project maintainer / owner. 😉

**Comment by weierophinney** [comment]
I'll check blog posts, but I don't think we mention pyrus anywhere in the current site other than old posts.

**Comment by froschdesign** [comment]
@weierophinney 
In the _old_ manual: https://framework.zend.com/manual/2.4/en/modules/zend.mvc.quick-start.html
