### ISSUE TITLE
Remove custom satis installation path from install instructions

### ISSUE THREAD

**Issue by Ocramius** [zendframework/zf-web#182]
Since packagist seems to be quite reliable, I don't see a reason to still suggest folks to point their `composer.json` definition at `packages.zendframework.com`

**Comment by froschdesign** [comment]
@weierophinney 
Must be changed in the (old) manual files on the server and in all related blog posts.

**Comment by weierophinney** [comment]
This is the wrong repo at this point, and I don't think the current web repo mentions packages.zendframework.com at all. As such, closing this one.
