### ISSUE TITLE
Missing Attachments in ZF1 Issue Archive

### ISSUE THREAD

**Issue by Stoyvo** [zendframework/zf-web#183]
Attachments are missing from this ticket but are still linked.
https://framework.zend.com/issues/browse/ZF-5063

Suggestions:
- Remove dead links
- Update attachment links with new file location

I recently learned this issue was imported from JIRA. Possibly an issue for all attachments from JIRA tickets?

**Comment by froschdesign** [comment]
I think, all attachment are no longer available. But the fix is already included:

> Status: Resolved Fix version(s): - 1.12.0 (27/Aug/12)

Btw. [ZF1 reaches its End of Life (EOL)](https://framework.zend.com/blog/2016-06-28-zf1-eol.html)

**Comment by Stoyvo** [comment]
Unfortunately large platforms like Magento still use ZF1, even their latest release.

These attachments are forever lost? I suggest removing the patch URLs to avoid future confusion.

**Comment by froschdesign** [comment]
> These attachments are forever lost? 

I think so, because to complete Jira installation is offline.

You can download different complete ZF1 version here from GitHub: https://github.com/zendframework/zf1/releases
