### ISSUE TITLE
Add breadcrumbs to docs and all other pages

### ISSUE THREAD

**Issue by froschdesign** [zendframework/zf-web#93]
![Breadcrumbs](https://f.cloud.github.com/assets/103362/429243/e1632cfc-ae3b-11e2-891f-357998388b7f.png)

**Comment by countless-integers** [comment]
:+1: looking forward to that.

**Comment by vrkansagara** [comment]
@froschdesign  this issue would be closed!

**Comment by froschdesign** [comment]
Fixed in the newer versions of the documentation.
